In [8]:
m16achine_learning = 1000


In [10]:
a=10
a+=12
print(a)

22


In [12]:
a=10
a/=12
print(a)

0.8333333333333334


In [18]:
a=100
b=200
print(a+b)
print(a-b)
print(b/a)

300
-100
2.0


In [26]:
a=int(input("enter a number"))
b=int(input("enter a number"))
print(a+b)

enter a number 10
enter a number 20


30


In [24]:
a=100
b=200
c=300
print(c>=b)
print(a>=b)
print(c>=a)

True
False
True


In [28]:
a=100
b=200
c=300
print(c>=b and a>b or b<c)
print(a>=b and c>a or c>b)
print(c>=a)

True
True
True


In [30]:
x=16
b=not x
print(b)

False


In [32]:
print(2==2)
print(3!=0)

True
True


In [36]:
otp=int(input("enter otp"))
if otp==234456:
        print('correct')
else:
        print('enter correct otp')
        

enter otp 234456


correct


In [44]:
a=12
b=78
if a<b: 
    print('true')

true


In [2]:
z="artificial intelligence"
z[9]

'l'

In [10]:
z[0:8:2]

'atfc'

In [18]:
z[2:3:4]

't'

In [23]:
z[10:0:-1]

' laicifitr'

In [25]:
z[::-1]      **

'ecnegilletni laicifitra'

In [44]:
a="name"
b="area"
print(a+b)
print(a*4)
print(b*10)


namearea
namenamenamename
areaareaareaareaareaareaareaareaareaarea


In [50]:
s="Modi was born and raised in Vadnagar in northeastern Gujarat, where he completed his secondary education. He was introduced to the RSS at the age of eight. At the age of 18, he was married to Jashodaben Modi, whom he abandoned soon after, only publicly acknowledging her four decades later when legally required to do so."
s.upper()

'MODI WAS BORN AND RAISED IN VADNAGAR IN NORTHEASTERN GUJARAT, WHERE HE COMPLETED HIS SECONDARY EDUCATION. HE WAS INTRODUCED TO THE RSS AT THE AGE OF EIGHT. AT THE AGE OF 18, HE WAS MARRIED TO JASHODABEN MODI, WHOM HE ABANDONED SOON AFTER, ONLY PUBLICLY ACKNOWLEDGING HER FOUR DECADES LATER WHEN LEGALLY REQUIRED TO DO SO.'

In [52]:
s="Modi was born and raised in Vadnagar in northeastern Gujarat, where he completed his secondary education. He was introduced to the RSS at the age of eight. At the age of 18, he was married to Jashodaben Modi, whom he abandoned soon after, only publicly acknowledging her four decades later when legally required to do so."
s.lower()

'modi was born and raised in vadnagar in northeastern gujarat, where he completed his secondary education. he was introduced to the rss at the age of eight. at the age of 18, he was married to jashodaben modi, whom he abandoned soon after, only publicly acknowledging her four decades later when legally required to do so.'

In [54]:
s="Modi was born and raised in Vadnagar in northeastern Gujarat, where he completed his secondary education. He was introduced to the RSS at the age of eight. At the age of 18, he was married to Jashodaben Modi, whom he abandoned soon after, only publicly acknowledging her four decades later when legally required to do so."
s.title()

'Modi Was Born And Raised In Vadnagar In Northeastern Gujarat, Where He Completed His Secondary Education. He Was Introduced To The Rss At The Age Of Eight. At The Age Of 18, He Was Married To Jashodaben Modi, Whom He Abandoned Soon After, Only Publicly Acknowledging Her Four Decades Later When Legally Required To Do So.'

LISTS

In [38]:
import spacy
nlp = spacy.load("en_core_web_sm")

In [4]:
sample = "Hi, My name is Mourya"

In [6]:
type(sample)


str

In [40]:
type(nlp(sample))

spacy.tokens.doc.Doc

In [10]:
sample.lower()

'hi, my name is mourya'

In [12]:
sample.split(' ')

['Hi,', 'My', 'name', 'is', 'Mourya']

In [18]:
tokens = sample.split(' ')

In [42]:
dir(nlp)

['Defaults',
 '__annotations__',
 '__call__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_components',
 '_config',
 '_disabled',
 '_ensure_doc',
 '_ensure_doc_with_context',
 '_factory_meta',
 '_get_pipe_index',
 '_has_gpu_model',
 '_link_components',
 '_meta',
 '_multiprocessing_pipe',
 '_optimizer',
 '_path',
 '_pipe_configs',
 '_pipe_meta',
 '_resolve_component_status',
 'add_pipe',
 'analyze_pipes',
 'batch_size',
 'begin_training',
 'component',
 'component_names',
 'components',
 'config',
 'create_optimizer',
 'create_pipe',
 'create_pipe_from_source',
 'default_config',
 'default_error_handler',
 'disable_pipe',
 'disable_pipes',
 'disabl

In [34]:
import spacy


nlp = spacy.load('en_core_web_sm')


stop_words = nlp.Defaults.stop_words
print(stop_words)


{'thence', 'together', 'former', 'but', 'using', 'more', 'himself', 'beforehand', 're', 'get', 'each', "'s", 'perhaps', 'of', 'anything', 'an', 'he', 'side', 'eleven', 'through', 'hereby', 'among', 'herself', 'yet', 'due', 'why', 'besides', 'amongst', 'who', 'everyone', 'this', 'whoever', 'as', 'she', 'regarding', 'am', 'someone', 'might', 'whether', 'five', 'both', 'seeming', 'hereupon', 'becomes', 'most', 'onto', 'upon', 'really', 'empty', 'via', 'nothing', 'yourself', 'or', 'thus', 'if', 'four', 'take', 'so', 'least', 'whom', 'neither', 'not', 'enough', 'after', 'thereupon', 'either', 'therefore', 'alone', 'from', 'yours', '’s', 'everything', 'around', "n't", 'how', '’m', 'hence', 'namely', 'anyway', 'doing', '‘d', 'too', 'his', 'go', 'used', 'must', 'across', 'mine', '’ll', 'done', 'our', 'here', 'three', 'can', 'else', 'n‘t', 'on', 'throughout', 'forty', '‘re', 'nobody', 'you', 'is', 'has', 'once', 'thru', 'ca', "'re", 'whereby', 'for', 'their', 'ourselves', 'elsewhere', 'some', "

In [6]:
from textblob import TextBlob
incorrect_text='certain conditions are during several ggenerations aare modified'

textBlb = TextBlob(incorrect_text)

textBlb.correct().string


'certain conditions are during several generations are modified'

In [18]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np
sentences = ["i love coding", "I love python", "Coding is fun"]
words = [sentence.split() for sentence in sentences]
vocabulary = sorted(set(word for sentence in words for word in sentence))
encoder = OneHotEncoder(sparse_output=False)
encoder.fit(np.array(vocabulary).reshape(-1, 1))
encoded_sentences = []
for sentence in words:
    encoded = encoder.transform(np.array(sentence).reshape(-1, 1))
    encoded_sentences.append(encoded)
print("Vocabulary:", vocabulary)
for i, sentence in enumerate(sentences):
    print(f"\nSentence: '{sentence}'")
    print("OneHotEncoded:\n", encoded_sentences[i])

Vocabulary: ['Coding', 'I', 'coding', 'fun', 'i', 'is', 'love', 'python']

Sentence: 'i love coding'
OneHotEncoded:
 [[0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]]

Sentence: 'I love python'
OneHotEncoded:
 [[0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]

Sentence: 'Coding is fun'
OneHotEncoded:
 [[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]]


In [14]:
documents=[" I love python  programming",
          "pyhton programming is fun",
          " I do not love the bugs in the code"]
from sklearn.feature_extraction.text import CountVectorizer
vectorizer=CountVectorizer()
bow_matrix=vectorizer.fit_transform(documents)
vocabulary=vectorizer.get_feature_names_out()
print(vocabulary)
print(bow_matrix.toarray())

['bugs' 'code' 'do' 'fun' 'in' 'is' 'love' 'not' 'programming' 'pyhton'
 'python' 'the']
[[0 0 0 0 0 0 1 0 1 0 1 0]
 [0 0 0 1 0 1 0 0 1 1 0 0]
 [1 1 1 0 1 0 1 1 0 0 0 2]]


In [ ]:
!

In [26]:
import pandas as pd
import numpy as np
documents=[" I love python  programming",
          "pyhton programming is fun",
          " I do not love the bugs in the code"]
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer=TfidfVectorizer()
X=vectorizer.fit_transform(documents)
df=pd.DataFrame(X.toarray(),columns=vectorizer.get_feature_names_out())

df.head()


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\MOURIYA DAMPETLA\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\Users\MOURIYA DAMPETLA\anaconda3\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\Users\MOURIYA DAMPETLA\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 701, in start
    self.io_loop.start()
  File "C:\Us

ImportError: 
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.



ImportError: numpy.core.multiarray failed to import

In [ ]:
import pandas as pd
import numpy as np
documents=[" I love python  programming",
          "pyhton programming is fun",
          " I do not love the bugs in the code"]
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer=TfidfVectorizer()
X=vectorizer.fit_transform(documents)
df=pd.DataFrame(X.toarray(),columns=vectorizer.get_feature_names_out())

df.head()

In [1]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer


documents = [
    "I Love python programming",
    "python programming is fun",
    "I do love bugs in code"
]

vectorizer = TfidfVectorizer()


x = vectorizer.fit_transform(documents)


df = pd.DataFrame(x.toarray(), columns=vectorizer.get_feature_names_out())

print(df.head())


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\Users\MOURIYA DAMPETLA\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "c:\Users\MOURIYA DAMPETLA\anaconda3\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "c:\Users\MOURIYA DAMPETLA\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 701, in start
    self.io_loop.start()
  File "c:\Us

ImportError: 
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.




A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\Users\MOURIYA DAMPETLA\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "c:\Users\MOURIYA DAMPETLA\anaconda3\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "c:\Users\MOURIYA DAMPETLA\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 701, in start
    self.io_loop.start()
  File "c:\Us

ImportError: 
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.



ImportError: numpy.core.multiarray failed to import

In [1]:
from  nltk import ngrams
text="i like java programming"
text=text.split()
print(text)

def n_gram(text,n):
    n_gram=ngrams(text,n)
    return[" ".join(grams) for grams in n_grams]


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\Users\MOURIYA DAMPETLA\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "c:\Users\MOURIYA DAMPETLA\anaconda3\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "c:\Users\MOURIYA DAMPETLA\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 701, in start
    self.io_loop.start()
  File "c:\Us

ImportError: 
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.




A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\Users\MOURIYA DAMPETLA\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "c:\Users\MOURIYA DAMPETLA\anaconda3\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "c:\Users\MOURIYA DAMPETLA\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 701, in start
    self.io_loop.start()
  File "c:\Us

ImportError: 
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.



['i', 'like', 'java', 'programming']
